name: galactic_football_league
description: "A new Flutter project for a simulated football league."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # Routing
  auto_route: ^10.1.0+1
  
  # Localization
  flutter_localization: ^0.3.3
  
  # Local Storage
  hive_ce: ^2.11.3

  # Models & Equality
  equatable: ^2.0.5
  
  # Utilities
  uuid: ^4.4.0
  intl: ^0.20.2

  # Device API
  vibration: ^3.1.3
  
  # UI
  cupertino_icons: ^1.0.6
  provider: ^6.1.5
  hive_ce_flutter: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.9
  auto_route_generator: ^10.2.3
  hive_ce_generator: ^1.0.1

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/