// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:galactic_football_league/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LeagueStandingAdapter());
    registerAdapter(MatchResultAdapter());
    registerAdapter(NewsItemAdapter());
    registerAdapter(TeamAdapter());
    registerAdapter(TeamDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LeagueStandingAdapter());
    registerAdapter(MatchResultAdapter());
    registerAdapter(NewsItemAdapter());
    registerAdapter(TeamAdapter());
    registerAdapter(TeamDtoAdapter());
  }
}
